server:
  port: 8080

spring:
  application:
    name: triform
     
  datasource:
    url: jdbc:sqlite:${user.dir}/data/triform.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "cBdq7eJHBJ/UQQePe32S+Wn/wDvTD9ikCytyxlSf9f0="
  expiration-ms: 3600000
